### ISSUE TITLE
Question: How is this different then OWASP OWTF

### ISSUE THREAD

**Issue by anantshri** [OWASP/glue#1]
How is this project different then OWASP OWTF.

OWTF also is automating web testing tools and i suppose pipeline is also doing the same. Please carify.

**Comment by mkonda** [comment]
Good question.  If I understand correctly, there is a bit of overlap, but pipeline is intended to be embedded in a build process.  So Jenkins could trigger pipeline processing a repo.  Or a simple web application with inventory (one such is to be open sourced soon ... ) that will run pipeline on any given repo.  Alternatively, one could set up git hooks to run pipeline.

So ... I think its really mostly the workflow around the tools and what happens after.  The target audience isn't really pen testers.  The target audience are devops folks that want to find ways to pull security into a build process / secure SDLC.

Does that make sense?  (Sorry for the slow response, somehow I missed this)
