### ISSUE TITLE
Glue JIRA reporter does not have Option to set JIRA Issue Type

### ISSUE THREAD

**Issue by tdshipley** [OWASP/glue#155]
**Summary**

Currently, Glue assumes when raising issues that they should be of type _Bug_. However not all JIRA projects might have this issue type so Glue should support overriding this if required.

**Pull Request**

Raised pull request #156 to fix.

**Comment by tdshipley** [comment]
#156 Has been merged which fixes the issue so closing this.

**Comment by tdshipley** [comment]
@omerlh - Hey do you know when the change in #156 will make it to the docker image owasp/glue:raw-latest as I don't seem to have the option in my container at the moment...

**Comment by tdshipley** [comment]
Never mind it is there - my local just wasn't using the latest!

**Comment by omerlh** [comment]
I'm glad to hear that!
