### ISSUE TITLE
Dockerfile build on master branch fails because of discontinued java8 PPA

### ISSUE THREAD

**Issue by PastNullInfinity** [OWASP/glue#162]
I'm trying to spin my own version of glue, taken directly from the Dockerfile of the master branch (as of the time of writing the latest commit is `e774c1612da17ab42caf3bb22663fc3a92880e5` ) instead of the DockerHub images, since there are some features that are still not in release yet.

While building the image I've encountered the following error:

```
Step 24/49 : RUN sudo apt-get install -y oracle-java8-installer
 ---> Running in 9e0f90dde1a7
Reading package lists...
Building dependency tree...
Reading state information...
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
The command '/bin/sh -c sudo apt-get install -y oracle-java8-installer' returned a non-zero code: 100
```

This is caused by the fact that the webupd8 PPA has been discontinued. 

A fix would be to switch to openJDK8, or to change the requirements to a higher version of Java (which, depending on what versions of the java-dependent tools will be integrated in the next version, could be an option.)

**Comment by omerlh** [comment]
I would vote for the first option (openJDK8) and have a separate issue about upgrading the Java version. I think it's mostly for Zap - so it's worth trying also to upgrade. Feel free to open a PR, I'll merge it.
