### ISSUE TITLE
Task that exit with error should set the exit code

### ISSUE THREAD

**Issue by omerlh** [OWASP/glue#66]
Task should be able to report a fatal error by setting the exit code. Currently I tried `Glue.error`, but it only reports the error and not setting the exit code to 1. I think that if task encounter fatal error, it should be detectable by the CI tool and the build should fail.

**Comment by mkonda** [comment]
Interesting.  So far we assume we will signal with the -z flag to send a signal if there are issues but I agree, if there is an error it should also fail.

Maybe we should add a fatal error level that exits immediately and sets that code.  Would that fit what you are thinking?

**Comment by omerlh** [comment]
Yeah, that sounds good to me. I could add a PR for that in the next few days hopefully...
